### PR TITLE
Fix memoryleaks

### PR DESCRIPTION
**Pull request by vladdeSV**
Also, cleaned up whitespace

### CODE REVIEW

**Comment by vladdeSV** [comment]
Should address my issue #25

**Comment by vladdeSV** [comment]
It should be more clear now what changes have been done, in the *Fix memoryleaks*

**Comment by JoshHawley** [comment]
@ToniCorinne These changes look good to me.

**Comment by JoshHawley** [comment]
@vladdeSV Thanks =)

**Comment by vladdeSV** [comment]
Will this be merged?

**Comment by ToniCorinne** [comment]
Apologies for the delay! Thank you for sharing your fixes with the community! It's greatly appreciated.

**Comment by vladdeSV** [comment]
Awesome! :+1:

**Pull request merged**
